name: "Style check"
description: "Style check using clang-format"

runs:
  using: "composite"
  steps:
    - name: "Run clang-format"
      shell: bash
      run: |
        # We only make check, not changes
        # Use the find command with the variable
        PROJECT_PATH=$(pwd)

        echo $PROJECT_PATH

        # Define los path donde estan los archivos que se quiere revisar su style
        # Primero define el path para los archivos en $PROJECT_PATH/src, luego para los archivos en $PROJECT_PATH/include y finalmente 
        # para los archivos en $PROJECT_PATH/libs
        SOURCE_FILES=$(find $PROJECT_PATH/src -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/include -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/libs -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")

        ERROR_FILE_FLAG=$PROJECT_PATH/clang-format_errors.txt

        # clang-format -i $SOURCE_FILES intenta formatear los archivos de SOURCE_FILES
        # En caso de que ocurra algun error redirige la stdout a clang-format_errors.txt
        CLANG_COMMAND=$(clang-format -i $SOURCE_FILES) > ${ERROR_FILE_FLAG}

        echo "Running: clang-format -i $SOURCE_FILES"

        if [ -s $ERROR_FILE_FLAG ]; then
            echo "Error: There are some files that are not formatted correctly"
            exit 1
        else
            echo "All files are formatted correctly. Niiiceee"
            exit 0
        fi

    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Clang-format errors!!!
        path: $PROJECT_PATH/clang-format_errors.txt
        retention-days: 1
